#!/usr/bin/env python3
from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    assert count == 1, (path, count, old[:120])
    p.write_text(text.replace(old, new, 1))


# 1) Candidate builder: bounded prior-period revision support.
builder = 'validation/build_macro_candidate.py'
replace_once(
    builder,
    '''    out = dict(c)\n    out["value"] = value\n    out["series_value"] = series_value\n    return out\n''',
    '''    out = dict(c)\n    out["value"] = value\n    out["series_value"] = series_value\n    prior_revision = c.get("prior_revision")\n    if prior_revision is not None:\n        if not isinstance(prior_revision, dict):\n            raise ValueError("prior_revision must be an object")\n        for key in ("observation_date", "before_value", "value"):\n            if prior_revision.get(key) in (None, ""):\n                raise ValueError(f"prior_revision missing {key}")\n        revision = dict(prior_revision)\n        if not isinstance(revision["observation_date"], str) or len(revision["observation_date"]) < 7:\n            raise ValueError("prior_revision observation_date must be YYYY-MM or YYYY-MM-DD")\n        revision["before_value"] = float(revision["before_value"])\n        revision["value"] = float(revision["value"])\n        revision["before_series_value"] = float(revision.get("before_series_value", revision["before_value"]))\n        revision["series_value"] = float(revision.get("series_value", revision["value"]))\n        for key in ("before_value", "value", "before_series_value", "series_value"):\n            if not math.isfinite(revision[key]):\n                raise ValueError(f"prior_revision {key} must be finite")\n        out["prior_revision"] = revision\n    return out\n'''
)
replace_once(
    builder,
    '''    if not isinstance(dates, list) or not isinstance(values, list) or len(dates) != len(values):\n        raise ValueError("target MACRO_SERIES entry has invalid dates/values")\n\n    storage_date, match_idx = resolve_storage_date(dates, obs_date, str(c["frequency"]))\n''',
    '''    if not isinstance(dates, list) or not isinstance(values, list) or len(dates) != len(values):\n        raise ValueError("target MACRO_SERIES entry has invalid dates/values")\n\n    prior_revision = c.get("prior_revision")\n    prior_revision_summary = None\n    if prior_revision is not None:\n        revision_date = str(prior_revision["observation_date"])\n        if same_period(revision_date, obs_date, str(c["frequency"])):\n            raise ValueError("prior_revision must precede the current observation")\n        revision_storage_date, revision_idx = resolve_storage_date(dates, revision_date, str(c["frequency"]))\n        if revision_idx is None or revision_idx != len(dates) - 1:\n            raise ValueError("prior_revision is allowed only for the immediately previous canonical period")\n        before_series_value = float(prior_revision["before_series_value"])\n        after_series_value = float(prior_revision["series_value"])\n        if abs(float(values[revision_idx]) - before_series_value) >= 1e-12:\n            raise ValueError("prior_revision series BEFORE value does not match the canonical input snapshot")\n        values[revision_idx] = after_series_value\n        prior_revision_summary = {\n            "observation_date": revision_date,\n            "storage_date": revision_storage_date,\n            "before_series_value": before_series_value,\n            "series_value": after_series_value,\n            "before_value": float(prior_revision["before_value"]),\n            "value": float(prior_revision["value"]),\n        }\n\n    storage_date, match_idx = resolve_storage_date(dates, obs_date, str(c["frequency"]))\n'''
)
replace_once(
    builder,
    '''    hist_values = [float(x) for x in hist]\n    detail_key = "unemployment" if dimension == "labour" else "inflation"\n    previous_as_of = heatmap["currencies"][currency].get("as_of_detail", {}).get(detail_key)\n    if same_period(previous_as_of, obs_date, str(c["frequency"])) and hist_values:\n''',
    '''    hist_values = [float(x) for x in hist]\n    detail_key = "unemployment" if dimension == "labour" else "inflation"\n    previous_as_of = heatmap["currencies"][currency].get("as_of_detail", {}).get(detail_key)\n    if prior_revision is not None:\n        if not hist_values or not same_period(previous_as_of, prior_revision["observation_date"], str(c["frequency"])):\n            raise ValueError("prior_revision heatmap period is not the immediately previous canonical period")\n        before_heat_value = float(prior_revision["before_value"])\n        after_heat_value = float(prior_revision["value"])\n        if abs(hist_values[-1] - before_heat_value) >= 1e-12:\n            raise ValueError("prior_revision heatmap BEFORE value does not match the canonical input snapshot")\n        hist_values[-1] = after_heat_value\n    if same_period(previous_as_of, obs_date, str(c["frequency"])) and hist_values:\n'''
)
replace_once(
    builder,
    '''        "series_action": action,\n        "history_observations": len(hist_values),\n''',
    '''        "series_action": action,\n        "prior_revision": prior_revision_summary,\n        "history_observations": len(hist_values),\n'''
)

# 2) Historical bootstrap: reconstruct the unrevised prior vintage, then replay revision + new point.
bootstrap = 'validation/macro_pit_historical_bootstrap.py'
replace_once(
    bootstrap,
    '''    require(("series_value" in previous) == ("series_value" in current), "previous/current series_value contract must be symmetric")\n    freq = str(manifest.get("frequency"))\n    require(freq in {"M", "Q"}, "bootstrap supports M/Q core series only")\n    require(period_key(previous["observation_date"], freq) < period_key(current["observation_date"], freq), "economic periods are not increasing")\n''',
    '''    require(("series_value" in previous) == ("series_value" in current), "previous/current series_value contract must be symmetric")\n    freq = str(manifest.get("frequency"))\n    require(freq in {"M", "Q"}, "bootstrap supports M/Q core series only")\n    prior_revision = manifest.get("prior_revision")\n    if prior_revision is not None:\n        require(isinstance(prior_revision, dict), "prior_revision must be an object")\n        for key in ("observation_date", "before_value", "value"):\n            require(prior_revision.get(key) not in (None, ""), f"prior_revision missing {key}")\n        for key in ("before_value", "value", "before_series_value", "series_value"):\n            if key in prior_revision:\n                require(math.isfinite(float(prior_revision[key])), f"prior_revision {key} is not finite")\n        require(period_key(prior_revision["observation_date"], freq) == period_key(previous["observation_date"], freq), "prior_revision must target manifest previous period")\n        require(abs(float(prior_revision["before_value"]) - float(previous["value"])) < 1e-12, "prior_revision before_value must equal previous official value")\n        previous_series_value = float(previous.get("series_value", previous["value"]))\n        revision_before_series = float(prior_revision.get("before_series_value", prior_revision["before_value"]))\n        require(abs(revision_before_series - previous_series_value) < 1e-12, "prior_revision before_series_value must equal previous official series value")\n    require(period_key(previous["observation_date"], freq) < period_key(current["observation_date"], freq), "economic periods are not increasing")\n'''
)
replace_once(
    bootstrap,
    '''    current_series_value = float(current.get("series_value", current["value"]))\n    previous_series_value = float(previous.get("series_value", previous["value"]))\n    require(period_key(dates[-1], freq) == period_key(current["observation_date"], freq), "canonical latest period differs from manifest current")\n    require(abs(float(values[-1]) - current_series_value) < 1e-12, "canonical latest series value differs from manifest current")\n    require(period_key(dates[-2], freq) == period_key(previous["observation_date"], freq), "penultimate canonical period differs from manifest previous")\n    require(abs(float(values[-2]) - previous_series_value) < 1e-12, "penultimate canonical series value differs from manifest previous")\n\n    removed_date, removed_value = dates.pop(), float(values.pop())\n    row["last_date"], row["last_value"] = dates[-1], values[-1]\n''',
    '''    current_series_value = float(current.get("series_value", current["value"]))\n    previous_series_value = float(previous.get("series_value", previous["value"]))\n    prior_revision = manifest.get("prior_revision")\n    canonical_previous_series_value = float(prior_revision.get("series_value", prior_revision["value"])) if prior_revision is not None else previous_series_value\n    require(period_key(dates[-1], freq) == period_key(current["observation_date"], freq), "canonical latest period differs from manifest current")\n    require(abs(float(values[-1]) - current_series_value) < 1e-12, "canonical latest series value differs from manifest current")\n    require(period_key(dates[-2], freq) == period_key(previous["observation_date"], freq), "penultimate canonical period differs from manifest previous")\n    require(abs(float(values[-2]) - canonical_previous_series_value) < 1e-12, "penultimate canonical series value differs from manifest previous/revision AFTER")\n\n    removed_date, removed_value = dates.pop(), float(values.pop())\n    if prior_revision is not None:\n        values[-1] = float(prior_revision.get("before_series_value", prior_revision["before_value"]))\n    row["last_date"], row["last_value"] = dates[-1], values[-1]\n'''
)
replace_once(
    bootstrap,
    '''    hist_values = [float(x) for x in hist]\n    require(abs(hist_values[-1] - float(current["value"])) < 1e-12, "heatmap history tail differs from current")\n    hist_values.pop()\n    require(abs(hist_values[-1] - float(previous["value"])) < 1e-12, "reconstructed heatmap tail differs from previous official value")\n\n    # The BEFORE state is intentionally reconstructed from the bounded canonical\n''',
    '''    hist_values = [float(x) for x in hist]\n    require(abs(hist_values[-1] - float(current["value"])) < 1e-12, "heatmap history tail differs from current")\n    hist_values.pop()\n    canonical_previous_heat_value = float(prior_revision["value"]) if prior_revision is not None else float(previous["value"])\n    require(abs(hist_values[-1] - canonical_previous_heat_value) < 1e-12, "reconstructed heatmap tail differs from previous/revision AFTER value")\n    if prior_revision is not None:\n        hist_values[-1] = float(prior_revision["before_value"])\n    require(abs(hist_values[-1] - float(previous["value"])) < 1e-12, "reconstructed heatmap tail differs from previous official value")\n\n    # The BEFORE state is intentionally reconstructed from the bounded canonical\n'''
)
replace_once(
    bootstrap,
    '''        "reconstructed_previous_value": row["last_value"],\n        "before_history_observations": len(hist_values),\n    }\n''',
    '''        "reconstructed_previous_value": row["last_value"],\n        "prior_revision_reconstructed": copy.deepcopy(prior_revision),\n        "before_history_observations": len(hist_values),\n    }\n'''
)
replace_once(
    bootstrap,
    '''    if "series_value" in current:\n        candidate["series_value"] = float(current["series_value"])\n    if row.get("unit") is not None:\n''',
    '''    if "series_value" in current:\n        candidate["series_value"] = float(current["series_value"])\n    prior_revision = manifest.get("prior_revision")\n    if prior_revision is not None:\n        candidate["prior_revision"] = {\n            "observation_date": str(prior_revision["observation_date"]),\n            "before_value": float(prior_revision["before_value"]),\n            "value": float(prior_revision["value"]),\n            "before_series_value": float(prior_revision.get("before_series_value", prior_revision["before_value"])),\n            "series_value": float(prior_revision.get("series_value", prior_revision["value"])),\n        }\n    if row.get("unit") is not None:\n'''
)

# 3) Unit tests: reconstruct unrevised BEFORE and replay revision + new observation.
test = 'validation/test_macro_pit_historical_bootstrap.py'
replace_once(
    test,
    '''from macro_pit_historical_bootstrap import reconstruct_before, validate_manifest\n''',
    '''from macro_pit_historical_bootstrap import candidate_from_manifest, reconstruct_before, validate_manifest\nfrom build_macro_candidate import apply_candidate\n'''
)
replace_once(
    test,
    '''    split_before_series, split_before_heat, _ = reconstruct_before(split_series, split_heat, split_manifest)\n    assert split_before_series["JPY"][0]["last_value"] == 332.813\n    assert split_before_heat["currencies"]["JPY"]["inflation"]["latest_value"] == 3.303856050706311\n\n    print("GMFQ_MACRO_PIT_HISTORICAL_BOOTSTRAP_TESTS_PASS")\n''',
    '''    split_before_series, split_before_heat, _ = reconstruct_before(split_series, split_heat, split_manifest)\n    assert split_before_series["JPY"][0]["last_value"] == 332.813\n    assert split_before_heat["currencies"]["JPY"]["inflation"]["latest_value"] == 3.303856050706311\n\n    revision_manifest = copy.deepcopy(manifest)\n    revision_manifest["previous"].update({"observation_date": "2026-07", "value": 1.9})\n    revision_manifest["current"].update({"observation_date": "2026-08", "value": 2.2})\n    revision_manifest["prior_revision"] = {\n        "observation_date": "2026-07",\n        "before_value": 1.9,\n        "value": 2.0,\n    }\n    revision_series, revision_heat = after_state()\n    revision_series["JPY"][0].update({\n        "values": [3.5, 3.3, 2.0, 2.2],\n        "last_value": 2.2,\n    })\n    revision_heat["currencies"]["JPY"]["inflation"].update({\n        "latest_value": 2.2,\n        "history": [3.5, 3.3, 2.0, 2.2],\n    })\n    revision_before_series, revision_before_heat, revision_meta = reconstruct_before(revision_series, revision_heat, revision_manifest)\n    assert revision_before_series["JPY"][0]["values"][-1] == 1.9\n    assert revision_before_series["JPY"][0]["last_value"] == 1.9\n    assert revision_before_heat["currencies"]["JPY"]["inflation"]["history"][-1] == 1.9\n    assert revision_before_heat["currencies"]["JPY"]["inflation"]["latest_value"] == 1.9\n    assert revision_meta["prior_revision_reconstructed"]["value"] == 2.0\n    revision_candidate = candidate_from_manifest(revision_manifest, revision_series)\n    assert revision_candidate["prior_revision"]["before_value"] == 1.9\n    assert revision_candidate["prior_revision"]["value"] == 2.0\n    replay_series = copy.deepcopy(revision_before_series)\n    replay_heat = copy.deepcopy(revision_before_heat)\n    result = apply_candidate(replay_series, replay_heat, revision_candidate)\n    assert result["prior_revision"]["before_value"] == 1.9\n    assert result["prior_revision"]["value"] == 2.0\n    assert replay_series["JPY"][0]["values"][-2:] == [2.0, 2.2]\n    assert replay_heat["currencies"]["JPY"]["inflation"]["history"][-2:] == [2.0, 2.2]\n\n    bad_revision = copy.deepcopy(revision_manifest)\n    bad_revision["prior_revision"]["observation_date"] = "2026-06"\n    expect_failure(lambda: validate_manifest(bad_revision), "prior_revision must target manifest previous period")\n\n    print("GMFQ_MACRO_PIT_HISTORICAL_BOOTSTRAP_TESTS_PASS")\n'''
)

print('REVISION_AWARE_REPLAY_PATCH_READY')
